modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/MoonflowerTeam/${repo}/issues"
license = "GPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Moonflower"
credits = "Jackson, Ocelot"
description = "A mod about locks"
displayURL = "https://www.moonflower.gg/"
logoFile = "logo.png"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "pollen"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "BEFORE"
side = "BOTH"